### ISSUE TITLE
A button for the mouse to go back in mods.

### ISSUE THREAD

**Issue by Arionic** [notweuz/FNF-OSEngine#13]
### What feature do you want to get added on the **base** engine?

A button for the mouse to go back in mods
Its frustrating that i can manage the mods easy with the mouse and to go back to menu i need to press backspace.

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support or Winning Icons.

**Comment by weuz-github** [comment]
will be added in 1.3.0
