### ISSUE TITLE
winning icons don't work

### ISSUE THREAD

**Issue by Lorekeeper49** [notweuz/FNF-OSEngine#22]
### Describe your bug here.

I place an icon image with a winning icon in the files and this happens (the whitty icon is the one that's broken):
![image](https://user-images.githubusercontent.com/93066594/170391057-9d7c5736-5733-484b-857f-9c99bf221fb0.png)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by notweuz** [comment]
only 450x150 winning icons are supported rn, maybe it's resolution is bigger

**Comment by Lorekeeper49** [comment]
> only 450x150 winning icons are supported rn, maybe it's resolution is bigger

so I need to edit the image by increasing the canvas size

**Comment by notweuz** [comment]
yeah
