### ISSUE TITLE
Week 7 cutscenes

### ISSUE THREAD

**Issue by Lorekeeper49** [notweuz/FNF-OSEngine#25]
### What needs to be documented?

They play, I know this is only a problem with OS because it doesn't happen on psych
[proof video](https://drive.google.com/file/d/1s4Q9KMRqJ3xBU402gwPS5MPYCGljFHfA/view?usp=sharing)

**Comment by notweuz** [comment]
os engine doesn't have any content related to original weeks, so ig it's the problem

**Comment by Lorekeeper49** [comment]
Well, I didn't change the source code at all, I only mod using Lua
