### ISSUE TITLE
Crashing near the end of a song.

### ISSUE THREAD

**Issue by Jaldabo** [notweuz/FNF-OSEngine#39]
### Describe your bug here.

The engine likes to crash near the end of a song for some reason. I'm using the most recent commit of FunkinLua.hx which had an issue causing some crashes, but it seems to still be occurring. Pretty certain its a Psych Engine issue, but its happening in OS Engine so I figured I'd make it known. I am able to reproduce the issue on Ballistic, so if anything there is useful, take it as you will. I'm 90% sure its a lua/animated sprite issue.
![Untitled](https://user-images.githubusercontent.com/104400900/175177175-5ff9cf2b-70d8-47ed-946c-e495dd444ce4.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Edited Playstate.hx for rating bar and some assets (shown above). Removed mentions of achivements and credits. (It is a personal, unshared build but the crashing should not be caused by these factors.)

**Comment by Jaldabo** [comment]
I was able to get a clip of it happening, and for this build, none of the source is edited/changed. Still prob a psych issue but sending it for the sake of documentation

https://user-images.githubusercontent.com/104400900/175398709-7f941e7e-9248-4300-8372-56af94807d7b.mp4

**Comment by Jaldabo** [comment]
https://drive.google.com/file/d/1ibXRZWe5F2JQJMqgd21iPg088qzUFG0E/view?usp=sharing Here you go :)
If you want the source stuff i can send it but nothing is changed outside of the assets
Also yeah prob not a mem issue since i'm running 16gb

**Comment by notweuz** [comment]
Thanks you. I'll check when I can

**Comment by TheLegion00** [comment]
seems like the crashes were caused by lua memory leaks which were fixed in the [newest release of psych](https://github.com/ShadowMario/FNF-PsychEngine/releases), ya might wanna merge or whatever. @notweuz
