### ISSUE TITLE
how do i even add wavy bg

### ISSUE THREAD

**Issue by bambitheone82112** [notweuz/FNF-OSEngine#40]
### What is your question?

so i realized os had shaders and so how do i make a wavy bg

**Comment by CrusherMods** [comment]
read stuff before you ask
![image](https://user-images.githubusercontent.com/90648119/175324099-399f5660-941f-40a8-99d1-16b8bf3d50e9.png)

**Comment by notweuz** [comment]
check out wiki (as CrusherMods said)
