### ISSUE TITLE
error while compiling last version

### ISSUE THREAD

**Issue by ModdedFNF** [notweuz/FNF-OSEngine#56]
### Describe your bug here.

when compiling the last version of OS engine i get this error:
source/FunkinLua.hx:346: lines 346-350 : Int should be Bool
source/FunkinLua.hx:346: lines 346-350 : ... For function argument 'f'
how to fix it??

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no, i just compile first the engine before do my changes

**Comment by decodinatorX** [comment]
Hey fam, I have a fix that worked for me, basically just uninstall linc_luajit by putting this into your cmd/powershell:
`haxelib remove linc_luajit`
Then you just need to reinstall it within cmd/powershell:
`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

**Comment by ModdedFNF** [comment]
thank you, it works perfectly
