### ISSUE TITLE
Int should be flixel.FlxObject  ... For function argument 'Object'

### ISSUE THREAD

**Issue by TheLegion00** [notweuz/FNF-OSEngine#60]
### Describe your bug here.

Not sure why but suddenly i've started getting a compiling bug after changing stuff in MainMenuState.hx. Any help to solve this would be appreciated!

### Command Prompt/Terminal logs (if existing)

```bash
source/MainMenuState.hx:282: characters 50-60 : Int should be flixel.FlxObject
source/MainMenuState.hx:282: characters 50-60 : ... For function argument 'Object'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I changed TitleState.hx and MainMenuState.hx, thats it.

**Comment by auroralash** [comment]
I just realised that it might be being caused by me changing the flicker colour from a variable, (magenta) to a hex code for yellow, (0xFFF1FF33) so i'll see if that was the issue.

**Comment by auroralash** [comment]
Okay so apparently i'm stupid and so now i'm just going to change magenta to yellow.
