### ISSUE TITLE
Source code does not compile at all

### ISSUE THREAD

**Issue by PG24Official** [notweuz/FNF-OSEngine#81]
### Describe your bug here.

So I'm trying to make a mod using the OS Engine source code, but it doesn't compile whatsoever. Can someone help me out? I tried compiling to Windows about 3-4 times already.

### Command Prompt/Terminal logs (if existing)

```bash
source/FunkinLua.hx:346: lines 346-350 : Int should be Bool
source/FunkinLua.hx:346: lines 346-350 : ... For function argument 'f'
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I was going to attempt adding song categorization in freeplay, but after trying to compile a fresh src copy, the same thing happened. So, it can't be because of that.

**Comment by lazyremixmanordummyplayinggmod** [comment]
get the lua jit its in the installation in readme in code and if not get updated haxe

**Comment by PG24Official** [comment]
Just reinstalled luajit and now everything is working fine. Thanks for the help!
